# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benny Hallett
email: ben@rojojo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Benny Hallett is a software engineer and entrepreneur that loves to learn new things and share them with people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bennyhallett.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
